public enum ParticleConfigurationType {
	None,
	MeleeDefault,
	HandgunDefault,
	MachinegunDefault,
	ShotgunDefault,
	CannonDefault,
	LauncherDefault,
	SplattergunDefault,
	SniperRifleDefault,
	UberMachineGun,
	EnigmaCannon,
	ParticleLance,
	ParticleLanceDE,
	FusionLance,
	SnapShot,
	MagmaRifle,
	HaloCannon
}
