public enum UberstrikeLayer {
	Default,
	TransparentFX,
	IgnoreRaycast,
	Water = 4,
	UI,
	GloballyLit = 8,
	GloballyLit_Reflect,
	GloballyLit_Refract,
	GloballyLit_ReflectRefract,
	GloballyLit_DynamicReflectRefract,
	LocallyLit,
	LocallyLit_Reflect,
	LocallyLit_Refract,
	LocallyLit_ReflectRefract,
	LocallyLit_DynamicReflectRefract,
	LocalPlayer,
	Weapons,
	RemotePlayer,
	Props,
	Trigger,
	Teleporter,
	RemoteProjectile,
	Controller,
	LocalProjectile,
	MeshGUI,
	Raidbot,
	Ragdoll,
	NGUI
}
